### ISSUE TITLE
Output of ls don't reveal colors for dirs nor files.

### ISSUE THREAD

**Issue by ghost** [altercation/solarized#1]
Hello,

Having problems using your color scheme for iTerm2 to display output with colors. Like colors for the `ls`output, etc.

How can I easily solve this?

PS. This is a bit unrelated, but I'm also unable to set the color scheme for MacVim to be light, not dark. SOLVED! Needed to set the `g:solarized_style` :)

Ed2t: To make the links in Vim display proper, I needed to set `let  :solarized_termtrans=1`. (When  starting Vim without file, you can see the exampels have links almost not displayed.

Also, when using the light scheme for iTerm2, I can see the text input.

Thank you.. Really like this scheme :D

**Comment by cztchoice** [comment]
@aantn fix it for me,too. But the preference is on prefs -> Profiles -> Text -> Draw bold text in bright colors. Deselect it.

**Comment by yangsuan** [comment]
@aantn +1 it worked for me ~ Thx

**Comment by xwjdsh** [comment]
@aantn Thanks.

**Comment by deeTEEcee** [comment]
@aaatn awesome

**Comment by parker789** [comment]
@aaatn still the fix!

**Comment by stgzr** [comment]
@aantn very helpful, thank u!

**Comment by Shourai** [comment]
@aantn +1
Fixes the issue when using GNU `ls`.
Had this problem when sshing to a linux box, where it didn't show any colors.
unticking
`Preferences-> Profiles -> Text -> Draw bold text in bright colors`
fixes it.
