### ISSUE TITLE
vim-colors-solarized breaks inside tmux

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [altercation/solarized#159]
The colorization goes all freaky-odd, but only when it's _inside_ tmux:
- http://ell.io/iaodn (outside tmux)
- http://ell.io/ichDH (inside tmux)

Notice, especially, the odd graphical glitches surrounding the number gutter where it meets the current line: http://ell.io/isv5X

It seems to expect “bright colours for bold text” to be enabled, but only inside tmux. When I enable that flag, the tmux-wrapped vim uses the correct colours, but the emboldening is off (left side; right side is vim outside tmux): http://ell.io/i9ae1

Both within and without tmux, `t_Co` is 16, as is `g:solarized_termcolors`.

**Comment by dmayle** [comment]
To add a final note, @klutzy has the *correct* solution, which is to use xterm-16color so that tmux knows you have a 16 color terminal.

**Comment by atddsd** [comment]
@coderarity's solution worked for me.

**Comment by simsalabim** [comment]
@coderarity's solution worked.

**Comment by danielcompton** [comment]
coderarity's solution worked for me too. Thanks! https://github.com/altercation/solarized/issues/159#issuecomment-5566892

**Comment by virtualsnake** [comment]
@coderarity it`s worked for me only after I remove TERM setting from my ~/.vimrc
Also for best experience next lines can be used in your .profiles or .bashrc:
```
if [ -n $TMUX ]; then
   alias vim="TERM=screen-256color vim"
fi
```
