### ISSUE TITLE
git colors don't look right

### ISSUE THREAD

**Issue by marr** [altercation/solarized#190]
Hi, 
I am using the solarized theme for iterm2 and I have some settings in my .gitconfig to use a color 'green bold' for example. What I see in iterm is actually just the same as normal text. Is there something I'm doing wrong that my colors wouldn't show up?

Thanks,
Dave

**Comment by jbenoit2011** [comment]
Same issue for me. Unchecking "Use bright colors for bold text" fixed it for me.

**Comment by gerhat** [comment]
I had the same issue on macOS 10.15.1 using:
- iTerm2 (Build 3.3.7)
- solarized dark
- oh my zsh

and fixed it by unchecking **Brighten bold text** in **Preferences > Profiles > Colors**
