### ISSUE TITLE
iTerm 2: Solarized Dark, zsh: Color of the comments is same as the background

### ISSUE THREAD

**Issue by icyflame** [altercation/solarized#351]
I am not sure why this is happening. has this problem been faced by someone before? If so, what was the fix?

**Comment by zeorin** [comment]
I have this same problem. I assume you're using zsh-syntax-highilghting plugin? It only happens with the Solarized Dark colour scheme?

Then it's this issue: https://github.com/altercation/solarized/issues/220. Basically, the `brblack` ANSI color in Solarized Dark is the same as the background color.

**Comment by icyflame** [comment]
@zeorin Absolutely, I have since switched to Solarized Light ( ❤️ ) and liked that as well. But I would love to get back to Solarized Dark.

That issue is pretty dense in terms of discussion, and it's name is also slightly misleading. (It didn't turn up in the searches I did before posting this issue.)

Closing this in favour of #220 .

**Comment by icyflame** [comment]
@zeorin Checked out the discussion, and found out about base16. It's a huge repository, and it's solarized dark theme works very well. Switched to that: https://raw.githubusercontent.com/chriskempson/base16-iterm2/master/base16-solarized.dark.256.itermcolors

in case you are interested.

**Comment by petern-sc** [comment]
Seconded, the repo above is deprecated, but using the newer fork colours are showing as expected
https://github.com/martinlindhe/base16-iterm2/tree/master/itermcolors
