### ISSUE TITLE
Let’s start a community-maintained fork: Sabattier

### ISSUE THREAD

**Issue by zeorin** [altercation/solarized#355]
Hello all,

The last commit to this project was over 3 years ago. At the time of writing this, there are 140 open issues, and 70 unmerged pull requests.

There’s even a bug that makes certain text *invisible*: #220, but fixing it would mean adjusting all applications’ dependent colorschemes, too.

Solarized is not only included as a pre-installed palette on e.g. Ubuntu, but it will likely soon be the default palette for [their new terminal](https://design.canonical.com/2016/08/convergent-terminal/)

This can’t last. I’ve been mulling over the idea of creating a proper fork that essentially fixes all the issues and merges the pull requests and will maintain this colorscheme into the future (because, despite its problems, it’s *awesome*).

I propose the following name: [Sabattier](https://en.wikipedia.org/wiki/Solarisation). With a wholly new name making backwards-incompatible changes and/or changes that require changes in colorschemes that depend on Solarized much easier to handle.

But I really don’t think a bus factor of 1 is such a great idea. Are there any other people who really love this colorscheme that would like to not see it become irrelevant and would like to participate in such a fork?

(I've also mailed @popey and @jounih of Canonical’s Convergent Terminal project to see what they think).

**Comment by greg0ire** [comment]
Have you asked to become a maintainer of this project?

**Comment by zeorin** [comment]
@greg0ire I have not, but @altercation has not responded to many mentions in the issues. I don't know why, but I assumed that he's not willing to engage with the community (and I'm not judging, either: these things happen).

I don't want to be a sole maintainer, either. The application colorschemes would be too much for me to handle. Hence my proposal for a community fork.

**Comment by greg0ire** [comment]
> @greg0ire I have not, but @altercation has not responded to many mentions in the issues. I don't know why, but I assumed that he's not willing to engage with the community (and I'm not judging, either: these things happen).

Sometimes, people don't respond because they have given up on reading their notification. Maybe you can find him on twitter, or find his email address in a commit, and shoot him an email?

>  don't want to be a sole maintainer, either. The application colorschemes would be too much for me to handle. Hence my proposal for a community fork.

The first thing you should do if you become a maintainer is look for new maintainers. If you can find some co-maintainers in this thread, then maybe write a grouped email. I'm sure @altercation would be glad to see his project live on and handle the keys.

**Comment by greg0ire** [comment]
If you don't think this can happen in real-life, see https://twitter.com/greg0ire/status/765486041209966592 and https://github.com/schmittjoh/JMSPaymentCoreBundle/issues/165

**Comment by zeorin** [comment]
@greg0ire OK, I will engage @altercation in other channels (e.g. email, twitter), once I have some indication of people that'd be willing to become maintainers.

**Comment by greg0ire** [comment]
If you don't find any, you can count on me! This is far from being my speciality, but I have experience maintaining open-source projects (reviewing PRs, writing contribution guide, and other meta issues). It would just be better to have more specialized maintainers.

**Comment by zeorin** [comment]
@greg0ire Is there a polite way to message or notify the authors of the outstanding pull requests and ask them whether they'd like to become maintainers? I'm considering mentioning this discussion in the comments of one pull request per pull requester, but it seems spammy.

**Comment by greg0ire** [comment]
Maybe ask [the top contributors](https://github.com/altercation/solarized/graphs/contributors) by mail instead?

**Comment by altercation** [comment]
Trevor and I have already been discussing some options to resolve this and are working on it.

**Comment by TrevorBramble** [comment]
@zeorin, @greg0ire: look for more very soon. we're not happy with the situation either and have been looking at possible solutions in recent weeks and want to make changes as soon as possible.

Thanks for your interest and patience.

**Comment by webfella** [comment]
Any update on this? I just had to setup a new laptop and forgot about all the annoying workarounds.

**Comment by zeorin** [comment]
@altercation @TrevorBramble Have you made any progress?

**Comment by mario-d-s** [comment]
I love Solarized and would be sad to see it die. There are practically no light themes for editors around but this one just _shines_, excuse the pun.

I'm only just getting started with open source but I'm offering my help here if there's anything I can do.

I'm a Windows dev so I use this primarily in Visual Studio, also Notepad++. But I'm interested in Linux so maybe I could help out with terminals and vim later.

Hoping for some evolution on this!

**Comment by studog-github** [comment]
@altercation @TrevorBramble @zeorin 
I have an outstanding bug fix: #367
I'm able to be a part-time maintainer.

**Comment by juanibiapina** [comment]
@zeorin still there? I love the idea of a fork with a new name, I'd be willing to start that right now if you're up.

**Comment by juanibiapina** [comment]
For now I'm testing this one: https://github.com/jan-warchol/selenized

It changes the background colors a little, reverses yellow and green highlights in vim (but there's an option to disable this) and tweaks other colors a little. I don't know if the background change is what effectively fixes the dark gray color problem or if that is solved by organizing colors in some other way (https://github.com/jan-warchol/selenized/blob/master/whats-wrong-with-solarized.md#better-terminal-compatibility). The vim plugin also works out of the box.
