### ISSUE TITLE
Forking solarized, merging existing patches and going forward

### ISSUE THREAD

**Issue by kbobyrev** [altercation/solarized#375]
Hi everyone!

Since there are many issues and even pull requests and the repo doesn't seem maintained anymore I've forked it into https://github.com/omtcyfz/solarized. I'll try to merge as many relevant pull requests as possible and fix some issues myself. If you would like to send an issue or help me out with the patches, please go ahead.

**Comment by Potherca** [comment]
You might want to try and collaborate with the folks over at #371 👍
