### ISSUE TITLE
output of `ls` does not show colors

### ISSUE THREAD

**Issue by yszhang95** [altercation/solarized#388]
The output of  `ls` does not show colors. No difference between text files and directories. I am using putty and I just execute [solarized_dark.reg](https://github.com/altercation/solarized/blob/master/putty-colors-solarized/solarized_dark.reg)

**Comment by capntrips** [comment]
I had the same problem.  Turns out you have to change _Window > Colours > Indicate bolded text by changing:_ from `The colour` to `The font`

**Comment by jgetfun** [comment]
@capntrips Thanks a lot! Your comment saved my problem in Windows 10 + KiTTY ( a fork of PuTTY).

**Comment by yszhang95** [comment]
It has been two years. So maybe I can close this issue?
