### ISSUE TITLE
iTerm2 ANSI bright colors are not actually bright

### ISSUE THREAD

**Issue by jeroenjacobs79** [altercation/solarized#397]
The colours selected under the "bright" colours are not actually bright (in fact, quite the opposite :-) ).

As a result, ANSI Art is not displayed correctly (for example: when using telnet to connect to an internet BBS).

**Comment by jeffbyrnes** [comment]
This is very similar to #376, you might find some guidance there for adjusting things for yourself.

Unfortunately, there doesn’t seem to be an “official” fix.

**Comment by jeroenjacobs79** [comment]
since there will be no fix, I'll close the ticket.
