### ISSUE TITLE
is this project active?

### ISSUE THREAD

**Issue by vrkansagara** [altercation/solarized#410]
I found many issues and PR are pending stat with vim solarized and this repo. so can any one tell me that. Does this repo is still valid into `2021` ?

**Comment by richtong** [comment]
If not who has an active fork :-)

**Comment by vrkansagara** [comment]
I thing maintainer need to take a call on this.

**Comment by richtong** [comment]
Yes, hopefully he will reply

Sent via Superhuman ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by waldyrious** [comment]
This issue is a duplicate of #299, btw.

**Comment by vrkansagara** [comment]
oh yes @waldyrious  lets close both issue #299 and #410
