### ISSUE TITLE
Pull request to update README.md

### ISSUE THREAD

**Issue by dampdigits** [altercation/solarized#418]
Hello there @weakish , I have used your [gist for Roxterm Solarized theme](https://gist.github.com/weakish/923039) & found it helpful. However, I propose to make some grammatical improvements and spelling corrections to your [README](https://gist.github.com/weakish/923039#file-readme-markdown).

This would probably be my first contribution, though it's not an improvement of code but I'm taking small steps in the world programming.

**Comment by shibor** [comment]
我应经收到你的邮件！

**Comment by dampdigits** [comment]
> 我应经收到你的邮件！

A reply in english would have been much better, but why would you receive my email?

**Comment by weakish** [comment]
> I propose to make some grammatical improvements and spelling corrections

Thanks a lot for fixing typos.
I merged your commits. :tada:

> I'm taking small steps in the world programming.

Welcome aboard.
I moved the gist to [github repo][0], so filing issues and pull requests will be more convenient.

> but why would you receive my email

I guess shibor subscribes to new issues of this repo (altercation/solarized) and the reply is an auto-reply from their email provider automatically trigged when a new email (in this case, GitHub notification email) is received in their inbox. And GitHub will automatically convert replies to notification email to issue replies.

[0]: https://github.com/weakish/roxterm-solarized-theme

**Comment by dampdigits** [comment]
> I guess shibor subscribes to new issues of this repo (altercation/solarized) and the reply is an auto-reply from their email provider automatically trigged when a new email (in this case, GitHub notification email) is received in their inbox. And GitHub will automatically convert replies to notification email to issue replies.

Understood, and thanks for the merge : )
