### ISSUE TITLE
iterm text color highlighting

### ISSUE THREAD

**Issue by rlayte** [altercation/solarized#71]
I've installed the color theme for iterm, which has worked for the background and standard text, but hasn't provided any color highlighting for file types, prompt, etc.

![iterm screenshot](http://farm6.static.flickr.com/5070/5630663171_c55c9699d5_b.jpg)

The colorscheme seems to be working in vim through iterm:

![vim screenshot](http://farm6.static.flickr.com/5069/5630663077_7e7d54b1b6_b.jpg)

**Comment by jfloff** [comment]
+1 You must add this to the README

**Comment by cheezer** [comment]
But after unchecking the "Draw bold text in bright color", the text are not bold any more. Can we have bold colored text?
