### ISSUE TITLE
Create a palette variation for red-green colorblind users

### ISSUE THREAD

**Issue by flavorjones** [altercation/solarized#91]
I'm red-green colorblind (protanopia), and I found it impossible to differentiate between "cyan" and "base0" -- i.e., in Emacs, the color used for strings was indistinguishable from normal text.

I found that increasing the blue aspect of "cyan" helped greatly -- see my fork's commit here: https://github.com/flavorjones/emacs-color-theme-solarized/commit/7c7b5aaab96765ffb269c7d98bd1e275baa353ef

But in general, I'm wondering if there's been any effort made to create variations of solarized for various colorblind users. I'd certainly be willing to assist by representing protanopes.

The science of colorblindness is relatively well understood (see http://dankaminsky.com/2010/12/15/dankam/ for the calculations behind the DanKam), so I'd love to see what can be done to make solarized more useful for colorblind people.

**Comment by Parakleta** [comment]
I have made a [variant](https://github.com/Parakleta/environment/tree/master/solarized-colourblind) that works for my particular colourblindness and makes each of the colours distinct, although it probably destroys the aim of the original solarized palette.

**Comment by sellout** [comment]
So, Emacs on OS X has now had sRGB support for two years, and my Solarized for Emacs has been using it for all of that time. If there are still issues with indistinguishable colors for colorblind users, I would be happy to hear about them on the sellout/emacs-color-theme-solarized repo. However, that should really only be for issues where you see the Emacs colors differ from the Vim ones.

If the problem also exists on Vim, @altercation sounds like he is happy to address it, and that’ll trickle down to Emacs afterward.

But it seems like perhaps this particular issue is resolved with the no-longer-new support of sRGB in Emacs.
